import { Inter } from "next/font/google";
import Provider from "/components/Provider";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <main className="bg-blue-900 min-h-screen flex">
            <Navbar />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
